### ISSUE TITLE
Run in UART in Raspberry Pi

### ISSUE THREAD

**Issue by leduynhat** [HighTemplar-wjiang/NIRScanner-Python#6]
Wonderful project I have to say.
BTW, is there any way I can run this project via UART port in Raspberry Pi

**Comment by HighTemplar-wjiang** [comment]
Thanks for trying my library! Unfortunately, my library does not include a UART implementation. 

Theoretically, you can use UART by integrating the UART driver from the official source code. Still, I would not recommend it as UART might be less reliable and more complex to implement for controlling the scanner unless you want to use a cheaper or low-power MCU kit like Arduino or MSP.
